### PR TITLE
Make file formatting comply with POSIX and Unix standards

### PR DESCRIPTION
**Pull request by aaronfranke**
UTF-8, LF, and no BOM are all recommended for file formatting. These settings are the most compatible with various tools and also take up the least amount of space (CRLF -> LF in a file means saving one byte per line, and no BOM saves two bytes per file). If the whole file has diffs, that's likely CRLF -> LF.

If you want to ensure future commits always use LF, you can use `git config --global core.autocrlf input` to tell Git to auto-convert to LF when committing files.

The POSIX standard for text files says that each text file should end with a newline, otherwise it is by definition not a text file. GitHub shows a warning when a file is committed without a terminating newline (see the "before" diffs of this PR), and GCC shows warnings when compiling files that don't end with newlines. See [this SO question](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/25322168) and [this Unix SE question](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) for more information. 

I only changed this in places where I'm sure it's a good change, just the C++ and txt files.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Pinging @kmammou @jratcliff63367

**Comment by aaronfranke** [comment]
Pinging @kmammou @jratcliff63367

There is another contribution I'd like to make to this repository too, but I'd prefer if this was merged first.

**Comment by akien-mga** [comment]
@aaronfranke I guess it's unnecessary after 2022 updates to this repo (or would need to be redone from scratch).

**Comment by aaronfranke** [comment]
I remade this PR, the diff is vastly smaller now (~5300 lines to ~50 lines), and I also added in a commit that losslessly optimizes PNG files using a tool called `oxipng`.

**Review by akien-mga — APPROVED** [review]
LGTM.

**Pull request merged**
